from routes.notificacoes import notificacoes_bp  # noqa: F401
from routes.bi import bi_bp  # noqa: F401
from routes.diario import diario_bp  # noqa: F401
from routes.auth import auth_bp  # noqa: F401
from routes.admin import admin_bp  # noqa: F401
from routes.sid import sid_bp  # noqa: F401
from routes.caixa import caixa_bp  # noqa: F401
from routes.servicos import servicos_bp  # noqa: F401
from routes.boletos import boletos_bp  # noqa: F401
from routes.lancamentos import lancamentos_bp  # noqa: F401
from routes.cronograma import cronograma_bp  # noqa: F401
from routes.orcamento_eng import orcamento_eng_bp  # noqa: F401
from routes.obras import obras_bp  # noqa: F401
from routes.superlink import superlink_bp  # noqa: F401
from routes.rh import rh_bp  # noqa: F401
from routes.frota import frota_bp  # noqa: F401
from routes.solicitacoes import solicitacoes_bp  # noqa: F401
from routes.home import home_bp  # noqa: F401
